### PR TITLE
Removed the ARIA menu and menuitem roles.

### LINKED ISSUE #10: The menu and menuitem roles on the toggle toolbar are an improper use of ARIA
This is not really a menu, at least not in the aria sense.  The ARIA standard is usually refering to pop-up menus when it uses this term.  In this case, all you have are a list of buttons that can be toggled, which is, IMHO, sufficiently conveyed via the current markup.

With the menu and menuitem roles, Jaws does not announce the pressed status of these buttons.  It just says that they are menu items, which is likely to be confusing to screen reader users, as they are expecting an entirely different interaction than what these buttons offer.

See https://www.w3.org/WAI/GL/wiki/Using_ARIA_menus for a sense of the sorts of things that these roles are properly used for.

### PR DESCRIPTION
**Pull request by cannona**
Fixes #10

### CODE REVIEW

**Comment by joedolson** [comment]
I'm committing this pull request, although I'm going to need to make at least one minor change; I need to have an ARIA role of some kind on this block of code, so that it doesn't become orphaned content. I'm not sure what I'm going to do for that. I'm considering using the 'form' role, although I'm going to have to test the user experience to see how appropriate that is.

**Comment by cannona** [comment]
I don't think the form role really makes sense here.  Perhaps a role of "region" and an aria-label of "accessibility toggles".  That way Jaws would read it as "Accessibility toggles region"?

**Comment by joedolson** [comment]
Problem with that is that 'region' isn't a landmark role, so it would still leave the toolbar as orphaned content, unavailable using landmark navigation. That said, I'm noticing that 'menu' isn't a landmark role, either, so I'm not actually making anything worse by removing the role. I think that this was at one time wrapped as a navigation role, and I changed that without considering the landmark issue.

**Comment by joedolson** [comment]
Now, testing, I'm also seeing that NVDA ignores the form landmark; so I think that's moot.

**Comment by cannona** [comment]
If you do decide to keep a landmark on this section, rest assured that region is absolutely a landmark role.  See this page from the WCAG Working Group:
https://www.w3.org/WAI/GL/wiki/Using_the_region_role_to_identify_a_region_of_the_page

**Pull request merged**
