### PR TITLE
Create wp-accessibility-pt_BR.po

### PR DESCRIPTION
**Pull request by theodorocaliari**
Hello Joe Dolson, first of all, thanks for develop this plugin. Well, I use your site for tranlate the plugin, and export this file from there. I try use this translation file in my theme but, without success... 
How can I activate it in theme? Thanks again....

### CODE REVIEW

**Comment by joedolson** [comment]
Thanks for creating the translation! I have to approve all the new translation strings, so the file you're including is actually empty; it doesn't include your translations, so it doesn't have any effect.. I'll take care of approving the strings and adding it in.

**Comment by joedolson** [comment]
Also, I'm going to close this request because I don't include the .po files in the plug-in; I'd prefer they were only used from my translations site. I only include the .mo file.

**Comment by theodorocaliari** [comment]
Thanks Joe... You rock
Em 10/01/2015 13:27, "Joe Dolson" <notifications@github.com> escreveu:

**Comment by joedolson** [comment]
The translation file is now approved, so you can download it at http://translate.joedolson.com/projects/wp-accessibility/pt-br/default. Download the .mo version and upload into the /lang directory of the plug-in. I'll get it added to my next release. Thank you!

**Comment by theodorocaliari** [comment]
After download .mo works! big hug from Brazil... best regards

**Pull request closed without merging**
